### PR TITLE
Added work by University of Modena

### PR DESCRIPTION
**Pull request by Bigazzon**

### CODE REVIEW

**Comment by ChanganVR** [comment]
Hi @Bigazzon thank you for contributing. I think adding this paper to the exploration section makes sense, but why Misc? Is there a reason?

**Comment by Bigazzon** [comment]
Hi Changan,
actually exploration section is also fine! I put it under Misc because it’s not completely focused on exploration since it also includes embodied captioning, but maybe it’s better to have it under exploration.

Thanks for reaching out to me.

Best,
Roberto Bigazzi

Da: Changan Chen
Inviato: venerdì 14 ottobre 2022 16:07
A: ChanganVR/awesome-embodied-vision
Cc: Roberto Bigazzi; Mention
Oggetto: Re: [ChanganVR/awesome-embodied-vision] Added work by University ofModena (PR #24)

Hi @Bigazzon thank you for contributing. I think adding this paper to the exploration section makes sense, but why Misc? Is there a reason?

**Comment by ChanganVR** [comment]
Great. In that case, could you push a new commit that removes it from Misc? I'll merge your PR after that.

**Comment by Bigazzon** [comment]
I forgot to change the title of the second paper I added, that's why it was confusing... But I put it under the exploration section anyways. Do you think it's fine?

**Comment by ChanganVR** [comment]
that is fine. But it looks they still have the same link to IEEE.

**Comment by Bigazzon** [comment]
Sorry about that, it should be ok now. Thanks for your patience.

**Pull request merged**
